// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4PBGhHoSEMtozngDazKjldFMUctCK9g',
    appId: '1:872574056955:web:f60b27a4de38db8503f35e',
    messagingSenderId: '872574056955',
    projectId: 'project-studyroom',
    authDomain: 'project-studyroom.firebaseapp.com',
    storageBucket: 'project-studyroom.appspot.com',
    measurementId: 'G-XD7HFQRZZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRWOxiDgED7pYodDiGdr3n4bXecm5jsQ',
    appId: '1:872574056955:android:57921b7c43cef5da03f35e',
    messagingSenderId: '872574056955',
    projectId: 'project-studyroom',
    storageBucket: 'project-studyroom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW9LcYxaO_sGG0QxTOLRFtozEmds1Re7k',
    appId: '1:872574056955:ios:508458e8c437a09f03f35e',
    messagingSenderId: '872574056955',
    projectId: 'project-studyroom',
    storageBucket: 'project-studyroom.appspot.com',
    iosBundleId: 'com.example.projectStudyroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW9LcYxaO_sGG0QxTOLRFtozEmds1Re7k',
    appId: '1:872574056955:ios:508458e8c437a09f03f35e',
    messagingSenderId: '872574056955',
    projectId: 'project-studyroom',
    storageBucket: 'project-studyroom.appspot.com',
    iosBundleId: 'com.example.projectStudyroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4PBGhHoSEMtozngDazKjldFMUctCK9g',
    appId: '1:872574056955:web:e9f89623ec20dbe603f35e',
    messagingSenderId: '872574056955',
    projectId: 'project-studyroom',
    authDomain: 'project-studyroom.firebaseapp.com',
    storageBucket: 'project-studyroom.appspot.com',
    measurementId: 'G-JRY7ZENLTN',
  );
}
